language: python
matrix:
  allow_failures:
  - os: osx
  include:
  - os: linux
    dist: trusty
    sudo: required
  - os: osx
    osx_image: xcode7.2
python:
- 2.7
#- 3.4
#- 3.5
#- 3.6
before_install: pip install codecov
install:
- make init
script:
- make test
after_success: codecov

